### ISSUE TITLE
Improve food component and list foods

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/go-restaurant-challenge#1]
## Description

Improve food component 

## Tasks 

- [x] Improve food component structure (Header & Footer)
- [x] Add `useFoods` hook to extract fetch logic  
- [x] Update food availability 
- [x] Add buttons to edit food and delete food 

## Notes 

Foods will be edited and deleted on other issues (to be created) so leave the buttons static for now

**Comment by LauraBeatris** [comment]
Be careful to not re-implement types because there are a lot implemented alright. Before creating one, search to see if it already exists and fits the case.
