### ISSUE TITLE
Delete food 

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/go-restaurant-challenge#10]
## Description 

Delete food 

## Tasks 

- [ ] Should open modal when clicking on the delete food icon 

![image](https://user-images.githubusercontent.com/48022589/98486975-338a2280-21ff-11eb-974f-7e910be5ad32.png)

- [ ] Call `useDeleteFood` hook
- [ ] Execute mutation when clicking on the confirmation modal
