### ISSUE TITLE
Implement button component

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/go-restaurant-challenge#15]
## Description

Implement a button component. It's being reused in many places of the app, such as modals and the header. 

## Tasks 

- [x] Add button component
- [x] Should have two variants - ``Primary`` and ``Secondary``
- [x] Remove unused styles related to button on Modals and other places

## Notes

Primary:

![image](https://user-images.githubusercontent.com/48022589/98569825-7eed1100-2291-11eb-8670-49a1ba20c80a.png)

Secondary:

![image](https://user-images.githubusercontent.com/48022589/98570858-a4c6e580-2292-11eb-9781-6d003253f4fc.png)

The icon should be passed as a property
