### ISSUE TITLE
Create food 

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/go-restaurant-challenge#7]
## Description 

Should create food after filling form modal 

![image](https://user-images.githubusercontent.com/48022589/98486545-acd44600-21fc-11eb-9d65-c8ede8bc58f2.png)

![image](https://user-images.githubusercontent.com/48022589/98486633-400d7b80-21fd-11eb-81c2-b18df5006200.png)

## Tasks 

- [x] Call `useCreateFoodMutation` hook 
- [x] Execute mutation to create a food on the form submit event 
- [x] If successfully created - Show the dark background with success icon above
