### ISSUE TITLE
Edit food 

### ISSUE THREAD

**Issue by LauraBeatris** [LauraBeatris/go-restaurant-challenge#9]
## Description 

Should edit food by filling the form modal 

## Tasks 

- [x] Should open edit food modal by clicking on the edit button 

![image](https://user-images.githubusercontent.com/48022589/98486680-9bd80480-21fd-11eb-9ae8-4e51af25c2e4.png)

- [x] Use the same form from the create food modal - Extract to a component in order to be reusable
- [x] Call `useEditFoodMutation` hook  
- [x] Execute mutation when submitting the form
